[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
